services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "learn"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: data
    logging:
      driver: none
