name: lint

on: workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Cached Checkout
        uses: actions/download-artifact@v3
        with:
          name: checkout-${{ github.run_id }}
      - uses: actions/setup-go@v5
        name: Install Golang
        with:
          go-version-file: "go.mod"
      - name: Test
        run: make test
